name: dart_api
description: dictionary application made with aqueduct.
version: 0.0.1
author: Lordvins <kevineilboudo54@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: 3.3.0+1
  postgres: ^1.0.0

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0